services:
  - type: web
    name: itgs-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn itgs_site.wsgi
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        value: changeme-super-secret-key
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
